import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import LqaNavbar from "../components/Header/LqaNavbar";
import LqaBody from "../components/Body/LqaBody";
import Footer from "../components/Footer/Footer";
import "mdb-react-ui-kit/dist/css/mdb.min.css";
import SnowfallEffect from "../components/SnowfallEffect";

export default function Home() {
    return (
        <div>
            <Head>
                <title>LQA</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://unpkg.com/aos@2.3.1/dist/aos.css"
                    rel="stylesheet"
                ></link>
            </Head>

            <SnowfallEffect />
            <LqaNavbar />
            <LqaBody />
            <Footer />
        </div>
    );
}
